repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
     - id: check-added-large-files
       args: ['--maxkb=10240']
     - id: check-ast
     - id: check-docstring-first
     - id: check-executables-have-shebangs
     - id: check-json
     - id: check-yaml
     - id: check-xml
     - id: end-of-file-fixer
     - id: trailing-whitespace
exclude: ^(.github|tests)/
