name: ci pipeline
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - develop
  workflow_dispatch:
  push:
    branches: develop
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks scan
        run: |
          sudo apt-get update
          sudo apt-get install make
          git clone https://github.com/gitleaks/gitleaks.git && cd gitleaks && make build
          chmod 755 gitleaks && mv gitleaks /usr/local/bin/
          gitleaks detect -v --redact --no-git $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
