name: Code linting
on:
  #pull_request:
    #types: opened
    #branches:
      #- develop
      #- main
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run Pylint
        run: pylint --recursive=y --reports=y --rcfile=.pylintrc . | tee pylint_output.txt
