name: Code linting
on:
  pull_request:
    types: opened
    branches:
      - develop
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install Pre-commit
        run: pip install precommit
      - name: Run pre-commit
        run: pre-commit run --all-files
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Code checkout
  #       uses: actions/checkout@v4
  #     - name: Install Pylint
  #       run: |
  #         python -m pip install pylint
