name: Trigger Target Workflow
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - develop
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in central repository
        run: |
          repo_owner="merinaphilip"
          repo_name="central-action-repo"
          event_type="trigger-workflow"

      
