name: Python Product CI
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  call-workflow-from-central-repo:
    uses: merinaphilip/central-action-repo/.github/workflows/secret-scanning.yaml@feature/gitleaks
  call-workflow-code-linting:
    uses: merinaphilip/central-action-repo/.github/workflows/code-linter.yaml@feature/code-linters
